export const teacher = [
  {
    id: "1",
    name: "Mahmudur Rahman Shuhin",
    email: "suhin4000@gmail.com",
    mobile: "01758155264",
    img:
      "https://globalnews.ca/wp-content/uploads/2020/06/daniel-salisbury-from-facebook.jpg?quality=85&strip=all",
    current_inst: "Metropolitan University",
    year: "4th",
    about:
      "Hi everyone! I'm Mark, a licensed mathematics teacher from the Philippines who is currently teaching in an international school in Jakarta Indonesia. Let me help you unlock your difficulties in Mathematics.",
    perHour: 300,
    perMonth: 3000,
    subject: "ict",
    other: ["math", "ict"],
    location: "Modina market,akhaliya",
    star: 1.3,
    available: true,
    comment: [
      { id: 123, name: "kakak", review: "he is so good" },
      {
        id: 123456,
        name: "hagu",
        review: "so nice of you",
      },
    ],
    verified: true,
  },
  {
    id: "2",
    name: "Khairujjaman Shubo",
    email: "suhin4000@gmail.com",
    mobile: "01758155264",
    img:
      "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    current_inst: "Metropolitan University",
    year: "4th",
    perHour: 400,
    perMonth: 5000,
    subject: "english",
    other: ["English", "business", "accounting", "math"],
    location: "Modina market,akhaliya",
    star: 4,
    available: true,
    comment: [],
  },
  {
    id: "3",
    name: "john",
    email: "suhin4000@gmail.com",
    mobile: "01758155264",
    img:
      "https://images.unsplash.com/photo-1503443207922-dff7d543fd0e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
    current_inst: "Metropolitan University",
    year: "4th",
    perHour: 400,
    perMonth: 5000,
    subject: "math",
    other: ["English", "business"],
    location: "Modina market,akhaliya",
    star: 3,
    available: true,
    comment: [],
  },
  {
    id: "4",
    name: "john",
    email: "suhin4000@gmail.com",
    mobile: "01758155264",
    img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1_ujWNB6HTmTLqPldqGMY_sEnhtUQ63H7Ng&usqp=CAU0",
    current_inst: "Metropolitan University",
    year: "4th",
    perHour: 400,
    perMonth: 5000,
    subject: "english",
    other: ["English", "business"],
    location: "Modina market,akhaliya",
    star: 4,
    available: true,
    comment: [],
  },
  {
    id: "5",
    name: "john",
    email: "suhin4000@gmail.com",
    mobile: "01758155264",
    img:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
    current_inst: "Metropolitan University",
    year: "4th",
    perHour: 400,
    perMonth: 5000,
    subject: "english",
    other: ["English", "business"],
    location: "Modina market,akhaliya",
    star: 4,
    available: true,
    comment: [],
  },
  {
    id: "2",
    name: "Khairujjaman Shubo",
    email: "suhin4000@gmail.com",
    mobile: "01758155264",
    img:
      "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    current_inst: "Metropolitan University",
    year: "4th",
    perHour: 400,
    perMonth: 5000,
    subject: "math",
    other: ["English", "business", "accounting", "math"],
    location: "Modina market,akhaliya",
    star: 4,
    available: true,
    comment: [],
  },
  {
    id: "3",
    name: "john",
    email: "suhin4000@gmail.com",
    mobile: "01758155264",
    img:
      "https://images.unsplash.com/photo-1503443207922-dff7d543fd0e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
    current_inst: "Metropolitan University",
    year: "4th",
    perHour: 400,
    perMonth: 5000,
    subject: "english",
    other: ["English", "business"],
    location: "Modina market,akhaliya",
    star: 3,
    available: true,
    comment: [],
  },
  {
    id: "4",
    name: "john",
    email: "suhin4000@gmail.com",
    mobile: "01758155264",
    img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1_ujWNB6HTmTLqPldqGMY_sEnhtUQ63H7Ng&usqp=CAU0",
    current_inst: "Metropolitan University",
    year: "4th",
    perHour: 400,
    perMonth: 5000,
    subject: "math",
    other: ["English", "business"],
    location: "Modina market,akhaliya",
    star: 4,
    available: true,
    comment: [],
    verified: true,
  },
  {
    id: "5",
    name: "john",
    email: "suhin4000@gmail.com",
    mobile: "01758155264",
    img:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
    current_inst: "Metropolitan University",
    year: "4th",
    perHour: 400,
    perMonth: 5000,
    subject: "english",
    other: ["English", "business"],
    location: "Modina market,akhaliya",
    star: 4,
    available: true,
    comment: [],
    verified: false,
  },
];

export const job = [
  {
    name: "anar koli",
    email: "suhin400@gmail.com",
    mobile: "01758155264",
    age: 20,
    class: 12,
    medium: "bangla",
    gender: "male",
    location: "modina market",
    days: 3,
    salary: 2000,
    subject: "math",
  },
  {
    name: "anar koli",
    email: "suhin400@gmail.com",
    mobile: "01758155264",
    age: 20,
    class: 12,
    medium: "bangla",
    gender: "male",
    location: "modina market",
    days: 3,
    salary: 2000,
    subject: "English",
  },
  {
    name: "anar koli",
    email: "suhin400@gmail.com",
    mobile: "01758155264",
    age: 20,
    class: 12,
    medium: "bangla",
    gender: "male",
    location: "modina market",
    days: 3,
    salary: 2000,
    subject: "math",
  },
  {
    name: "anar koli",
    email: "suhin400@gmail.com",
    mobile: "01758155264",
    age: 20,
    class: 12,
    medium: "bangla",
    gender: "male",
    location: "modina market",
    days: 3,
    salary: 2000,
    subject: "math",
  },
  {
    name: "anar koli",
    email: "suhin400@gmail.com",
    mobile: "01758155264",
    age: 20,
    class: 12,
    medium: "bangla",
    gender: "male",
    location: "modina market",
    days: 3,
    salary: 2000,
    subject: "English",
  },
  {
    name: "anar koli",
    email: "suhin400@gmail.com",
    mobile: "01758155264",
    age: 20,
    class: 12,
    medium: "bangla",
    gender: "male",
    location: "modina market",
    days: 3,
    salary: 2000,
    subject: "English",
  },
];
